/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#fbf9fc",
        "primary-fixed": "#fdd6ff",
        "inverse-surface": "#303033",
        "error-container": "#ffdad6",
        "tertiary-container": "#c6a851",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#241a00",
        "surface-dim": "#dbd9dc",
        background: "#fbf9fc",
        "surface-variant": "#e3e2e5",
        "on-error": "#ffffff",
        "on-surface-variant": "#504251",
        "outline-variant": "#d4c1d3",
        "on-secondary-container": "#735e73",
        secondary: "#6c586d",
        "on-tertiary-container": "#4f3d00",
        "on-primary-fixed-variant": "#790095",
        "surface-container": "#efedf0",
        primary: "#71008c",
        "on-secondary-fixed-variant": "#544155",
        "on-primary": "#ffffff",
        outline: "#827282",
        "surface-bright": "#fbf9fc",
        "secondary-fixed": "#f5daf4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f6",
        "on-secondary-fixed": "#261628",
        tertiary: "#735c06",
        "on-surface": "#1b1b1e",
        "on-primary-fixed": "#340042",
        "on-background": "#1b1b1e",
        "tertiary-fixed-dim": "#e3c469",
        error: "#ba1a1a",
        "inverse-primary": "#f4aeff",
        "inverse-on-surface": "#f2f0f3",
        "primary-container": "#9317b2",
        "surface-tint": "#9920b8",
        "primary-fixed-dim": "#f4aeff",
        "surface-container-high": "#e9e7ea",
        "surface-container-highest": "#e3e2e5",
        "on-primary-container": "#f7bdff",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffe08b",
        "on-tertiary-fixed-variant": "#584400",
        "on-tertiary": "#ffffff",
        "secondary-container": "#f5daf4",
        "secondary-fixed-dim": "#d8bfd7",
        ink: "#0a010d",
        border: "#cdcdcd",
      },
      borderRadius: {
        /** Editorial: inputy / tlačítka ~md, karty ~xl (design system) */
        geist: "5px",
        "geist-card": "8px",
        "geist-panel": "12px",
        DEFAULT: "0.75rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        /** Legacy neutrální stíny */
        "geist-sm": "0 2px 4px rgba(0, 0, 0, 0.1)",
        "geist-md": "0 4px 14px 0 rgba(0, 0, 0, 0.1)",
        "geist-lg": "0 30px 60px rgba(0, 0, 0, 0.12)",
        /** Editorial: ambient, tónované primary (~4 %, velký blur) */
        "editorial-sm": "0 2px 16px rgba(113, 0, 140, 0.06)",
        "editorial-md": "0 8px 40px rgba(113, 0, 140, 0.04)",
        "editorial-lg": "0 16px 48px rgba(113, 0, 140, 0.06)",
      },
      fontFamily: {
        sans: [
          "Geist Sans",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "sans-serif",
        ],
        headline: [
          "Geist Sans",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "sans-serif",
        ],
        body: [
          "Geist Sans",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "sans-serif",
        ],
        label: [
          "Geist Sans",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "sans-serif",
        ],
      },
      letterSpacing: {
        "geist-heading": "-0.02em",
      },
      lineHeight: {
        "geist-tight": "1.2",
        "geist-body": "1.5",
      },
      maxWidth: {
        /** Geist: obsah ~1000–1200px */
        "geist-content": "72rem",
      },
      fontSize: {
        /** Geist: delší text / obsah 16px */
        "geist-content": ["1rem", { lineHeight: "1.5" }],
      },
    },
  },
  plugins: [],
};
